// Home page sections, one per traditional category (in display order).
// `cover` is a category id used to pick the section's cover photo.
export const HOME_SECTIONS = [
  {
    id: "regular-mithai",
    label: "Regular Mithai",
    eyebrow: "The Mithai Counter",
    title: "Everyday mithai,",
    accent: "made fresh.",
    blurb: "Gulab Jamun, Cham Cham, Barfi, Laddu and more, the sweets every Karachi household reaches for.",
    cta: "See all mithai",
  },
  {
    id: "special-mithai",
    label: "Special Mithai & Boxes",
    eyebrow: "Premium & Gifting",
    title: "Special mithai,",
    accent: "boxed to gift.",
    blurb: "Kaju Katli, Akhrot Halwa and ready-to-give gift packs for Eid, weddings and thank-yous.",
    cta: "Explore premium boxes",
  },
  {
    id: "halwajaat",
    label: "Halwajaat",
    eyebrow: "Halwa Counter",
    title: "Slow-cooked",
    accent: "halwajaat.",
    blurb: "Sohn Halwa, Multani Halwa, Habshi Halwa and other traditional favourites, cooked patiently in ghee.",
    cta: "See all halwa",
  },
  {
    id: "nimco",
    label: "Nimco & Savories",
    eyebrow: "Nimco & Savories",
    title: "Crunch worth",
    accent: "coming back for.",
    blurb: "Mix Nimco, Dal Moth, Cheevda, Sev and other crisp, spiced snacks, sold by weight.",
    cta: "See all nimco",
  },
  {
    id: "baked-snacks",
    label: "Baked Items & Snacks",
    eyebrow: "Fresh From The Oven",
    title: "Samosa, rolls",
    accent: "& patties.",
    blurb: "Hot, flaky and filled: samosas, rolls and patties for lunchboxes, tea and iftar tables.",
    cta: "See baked snacks",
  },
  {
    id: "biscuits",
    label: "Biscuits & Cookies",
    eyebrow: "Biscuit Jar",
    title: "Biscuits &",
    accent: "cookies.",
    blurb: "Bakery biscuits, buttery Nan Khatai and cookies, baked in small batches.",
    cta: "See biscuits",
  },
  {
    id: "bread-rusk",
    label: "Bread & Rusk",
    eyebrow: "Daily Bread",
    title: "Fresh bread,",
    accent: "crisp rusk.",
    blurb: "Soft loaves and buns baked through the day, plus Cake Rusk and Plain Rusk for chai.",
    cta: "See bread & rusk",
  },
  {
    id: "tea-cakes",
    label: "Tea Cakes & Pastries",
    eyebrow: "Tea-Time",
    title: "Tea cakes &",
    accent: "pastries.",
    blurb: "Loaf cakes for the tea tray and pastries for a sweet finish.",
    cta: "See cakes & pastries",
  },
];
